baseURL = "https://adpit.github.io/arie_digital/"
languageCode = "en-us"
title = "Arie Digital 2"
theme = "hugo-theme-relearn"

[[menu.main]]
name = "Beranda"
url = "/"
weight = 1
[[menu.main]]
name = "Basics"
identifier = "basics"
url = "/basics/"
weight = 10
[[menu.main]]
name = "Content"
parent = "basics"
url = "/basics/content/"
weight = 10
[[menu.main]]
name = "Shortcodes"
parent = "basics"
url = "/basics/shortcodes/"
weight = 20

[permalinks]
  posts = "/:year/:month/:day/:slug"
