backend:
  name: github
  repo: adpit/arie_digital # Gantikan dengan repo GitHub Anda
  base_url: https://api.netlify.com
  auth_endpoint: auth
  branch: master    # Branch to update
  # base_url: https://adpit.github.io/arie_digital

media_folder: "static/images/uploads" 
public_folder: "/images/uploads"
collections:
  - name: "posts" 
    label: "Posts" 
    folder: "content/posts" 
    create: true 
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }



